Path-Check/safeplaces-frontend

js/location-scrubber.js
PR for https://github.com/Path-Check/safeplaces-frontend/issues/7
https://github.com/tripleblindmarket/safe-places/issues/56
What has changed ?
created isValidJson function 
New error type {type:'File Error'}
Trying to do a global catch, for all unexcepted errors showing the actual error to users
Linting
=> add error Type File Error

.github/workflows/google.yml
Automated deployment of branch: dev_mvp into a development enviornment over gke and to host : [https://safeplaces.extremesolution.com](https://safeplaces.extremesolution.com)
=> automated deployment of dev_mvp to GKE

.gitignore, Safe-Places-Server.md
modded Server spec to support GET and SET of organization attributes
=> Dev mvp issue26

js/publisher.js, publisher/index.html
closes #26 on the front-end side.  Needs backend to support new dev_mvp Server spec to verify
=> added support for issue #26

css/style.css
=> made date slider fonts small

css/style.css, location-scrubber/index.html, publisher/index.html
=> fixed color styles for readability and added lang attr to HTML tag

.babelrc, README.md, js/config.js, js/lib.js, js_es5/config.js, js_es5/lib.js, js_es5/location-scrubber.js, js_es5/publisher.js, location-scrubber/index.html, package-lock.json, package.json, publisher/index.html
=> Dev mvp issue43

css/style.css, js/location-scrubber.js, js/publisher.js
=> added extra contreast to filter dates text

README.md
=> Project status note added to README

src/components/EntryForm/index.js
This resolves #67.
Demo of the visual change:
=> Add tooltips to add entry dialog (#67)

CONTRIBUTING.md
=> Adds contribution guidelines

src/components/AddNewRecord/AddNewRecord.module.scss, src/components/AddNewRecord/AddNewRecord.stories.js, src/components/AddNewRecord/index.js, src/components/Button/index.js, src/components/Button/styles.module.scss, src/components/Dialog/Dialog.module.scss, src/components/Dialog/index.js, src/components/Modal/index.js, src/components/Modal/styles.module.scss
**Add New Record modal**
Pull request contains a static/dumb component build for the Add New Record modal present in the latest [designs](https://www.figma.com/file/MlHKMJ02695qR2wsPByHCr/PLACES-%2F-April-2020?node-id=214%3A2615). 
The component currently consumes props from a storybook story, however props will eventually be provided by the global store which will be hydrated via async. operations related to adding a new record to the database.
**Stories**
The following are screenshots of UI stories from storybook.
The component does not contain any significant logic or trigger async. operations, but once the FE can post a new record to the API this will change.
[JIRA ticket](https://pathcheck.atlassian.net/browse/PLACES-159)
=> [PLACES-159] Add New Record modal (UI only)

src/components/Button/index.js, src/components/Button/styles.module.scss, src/components/Dialog/Dialog.module.scss, src/components/Dialog/index.js, src/components/Modal/index.js, src/components/Modal/styles.module.scss, src/components/RecordAdded/RecordAdded.module.scss, src/components/RecordAdded/RecordAdded.stories.js, src/components/RecordAdded/index.js
**New Record Added modal**
Pull request contains a static/dumb component build for the New Record Added modal  present in the latest [designs](https://www.figma.com/file/MlHKMJ02695qR2wsPByHCr/PLACES-%2F-April-2020?node-id=214%3A2615). 
The component currently consumes props from a storybook story, however props will eventually be provided by the global store which will be hydrated via async. operations related to adding a new record to the database.
**Stories**
The following are screenshots of UI stories from storybook.
The component does not contain any significant logic or trigger async. operations, but once the FE can post a new record to the API this will change.
[JIRA ticket](https://pathcheck.atlassian.net/browse/PLACES-178)
=> [PLACES-178]  New Record Added modal (UI only)

.eslintrc.json, src/components/RedactorTools/DateSelector/DateSelector.stories.js, src/components/RedactorTools/DateSelector/SingleDateToggle/SingleDateToggle.module.scss, src/components/RedactorTools/DateSelector/SingleDateToggle/index.js, src/components/RedactorTools/DateSelector/dateSelector.module.scss, src/components/RedactorTools/DateSelector/index.js, src/components/Sidebar/SidebarWrapper/index.js, src/components/Sidebar/SidebarWrapper/sidebarWrapper.module.scss
**Date Selection Filter**
Pull request contains a static/dumb component build for the Date Selection Filter present in the latest [designs](https://www.figma.com/file/MlHKMJ02695qR2wsPByHCr/PLACES-%2F-April-2020?node-id=214%3A2615). 
**Stories**
The following are screenshot(s) of UI stories from storybook.
The component does not contain any significant logic or trigger async. operations, but once the FE can post a new record to the API this will change.
**Assumptions**
API will provide array of dates based on GPS data 
[JIRA ticket](https://pathcheck.atlassian.net/browse/PLACES-215)
=> [PLACES-215] Date Selection Filter (UI only)

src/components/Checkbox/Checkbox.js, src/components/Checkbox/styles.module.scss, src/components/RedactorTools/FilterData/DurationFilter/DurationFilter.module.scss, src/components/RedactorTools/FilterData/DurationFilter/DurationFilter.stories.js, src/components/RedactorTools/FilterData/DurationFilter/index.js, src/components/RedactorTools/FilterData/FilterData.module.scss, src/components/RedactorTools/FilterData/FilterData.stories.js, src/components/RedactorTools/FilterData/index.js, src/scss/global.scss
**Duration Filter**
Pull request contains a static/dumb component build for the Duration Filter present in the latest [designs](https://www.figma.com/file/MlHKMJ02695qR2wsPByHCr/PLACES-%2F-April-2020?node-id=214%3A2615). 
**Stories**
The following are screenshot(s) of UI stories from storybook.
The component does not contain any significant logic or trigger async. operations, but once the FE can post a new record to the API this will change.
[JIRA ticket](https://pathcheck.atlassian.net/browse/PLACES-221)
=> [PLACE-221] Duration Filter (UI only)

src/components/Sidebar/SidebarActions/index.js, src/views/Publishing/Actions/PublishingActions.module.scss, src/views/Publishing/Actions/PublishingActions.stories.js, src/views/Publishing/Actions/index.js, src/views/Tracer/Actions/TracerActions.module.scss, src/views/Tracer/Actions/TracerActions.stories.js, src/views/Tracer/Actions/index.js
This PR contains the main CTAs for the publishing and tracer sections of the app;
Once merged development can being on the Add New/Load from Database application flows.
=> Sidebar Actions (UI only)

package.json, src/components/Button/index.js, src/components/HAConfig/Map/index.js, src/components/HAConfig/Map/layers.js, src/components/HAConfig/Map/style.json, src/components/HAConfig/Map/styles.module.scss, src/components/HAConfig/MapModal/index.js, yarn.lock
Not fully developed, but fixes geocode issues and adds CTA to component
=> HA Map changes

src/components/_legacy/EntryForm/index.js, src/components/_legacy/Filter/index.js, src/components/_legacy/PathEditor/Dropzone.js, src/components/_legacy/Sidebar/index.js, src/components/_legacy/Wrapper/index.js, src/components/_shared/Map/Popup/index.js, src/components/_shared/Map/index.js, src/components/_shared/RedactorTools/DateSelector/index.js, src/ducks/record/actions.js, src/ducks/record/reducer.js, src/ducks/record/sagas.js, src/ducks/record/service.js, src/ducks/record/types.js, src/sagas.js, src/views/Onboarding/HAConfig/Map/index.js, src/views/Trace/AddNewRecord/index.js
**Delete New Record**
Pull request contains the necessary code to facilitate the deletion of a new record prior to the manual creation, or polling for GPS data from a mobile device.
@FacundoMalgieri please let me know if you want me to walk through in the running application.
The following are screenshots of the user journey from the actual application;
**Step 1 - Hit 'Add New Record' CTA**
**Step 2 - Hit 'Cancel' CTA**
All async. operations currently deal with the Mock API; the request configs and endpoints are subject to change.
[JIRA ticket](https://pathcheck.atlassian.net/browse/PLACES-238)
=> [PLACES 238] Delete New Record

src/components/_shared/Map/Marker/Marker.module.scss, src/components/_shared/Map/Marker/index.js, src/components/_shared/Map/index.js, src/components/_shared/PointContextMenu/index.js, src/components/_shared/SelectedData/SelectedDataItem/SelectedDataItem.module.scss, src/components/_shared/SelectedData/SelectedDataItem/index.js, src/components/_shared/SelectedData/index.js, src/ducks/cases/sagas.js, src/ducks/index.js, src/ducks/points/actions.js, src/ducks/points/reducer.js, src/ducks/points/sagas.js, src/ducks/points/selectors.js, src/ducks/points/service.js, src/ducks/points/types.js, src/store.js, yarn.lock
**Highlight Point via List and Map**
Pull request contains codebase additions which provide the user with the following capabilties;
- Highlight a point of concern via the sidebar.
- Highlight a point of concern via the map.
**This PR does not concern itself with CRUD operations related to PoCs.**
@FacundoMalgieri please let me know if you want me to walk through in the running application.
The following are screenshots of the user journey from the actual application;
[JIRA ticket PLACES-119)](https://pathcheck.atlassian.net/browse/PLACES-119)
[JIRA ticket PLACES-120)](https://pathcheck.atlassian.net/browse/PLACES-120)
=> [PLACES 119-120] Highlight Point via List and Map

src/ducks/auth/actions.js, src/ducks/auth/reducer.js, src/ducks/auth/service.js, src/ducks/auth/types.js, src/views/Onboarding/HAConfig/DaySlider/index.js, src/views/Onboarding/HAConfig/MapModal/index.js, src/views/Onboarding/HAConfig/index.js, src/views/Onboarding/HAConfig/infoInputs.js, src/views/Onboarding/index.js, src/views/Settings/index.js, src/views/Settings/styles.module.scss
Also fixes [PLACES-271](https://pathcheck.atlassian.net/browse/PLACES-271) and [PLACES-269](https://pathcheck.atlassian.net/browse/PLACES-269)
=> [PLACES-262] Settings Sidebar (Logout User and other options)

src/axiosInterceptors.js, src/components/_shared/SelectedData/SelectedData.module.scss, src/components/_shared/SelectedData/index.js, src/views/Authentication/Login/index.js
=> [PLACES-341] Deselect Point(s) of Concern - ALL

src/components/_global/errorBoundary.jsx, src/components/_shared/Map/index.js, src/views/Onboarding/HAConfig/Map/index.js, src/views/Publish/index.js, src/views/Trace/index.js
Currently the FE doesn't handle `null` values when dealing with fitting the map to a bounding box via the `regionsCoordinates`. **It used to be that the API would default to `0` for each coord, opposed to `null`**
=> [PLACES-370] Ensure frontend defends against null values for regionsCoords.

src/components/_shared/Map/index.js, src/views/Onboarding/HAConfig/Map/index.js
I caught an error in the HA map earlier today, this defends against a complete absence of value.
=> Map init. error catch

src/components/_shared/Checkbox/Checkbox.js, src/components/_shared/Checkbox/styles.module.scss, src/components/_shared/ControlledCheckbox/Checkbox.js, src/components/_shared/ControlledCheckbox/styles.module.scss, src/components/_shared/RecordsTable/RecordsTablePublishing/Record/index.js, src/components/_shared/RecordsTable/RecordsTablePublishing/index.js, src/components/_shared/RedactorTools/FilterData/RecordIdsFilter/index.js, src/components/_shared/RedactorTools/FilterData/index.js, src/components/_shared/RedactorTools/index.js, src/scss/global.scss
**Filter Data by Record ID**
Pull request contains codebase additions which provide the user with the ability to filter the staged location data using the API generated `caseId`s
[Demo](https://drive.google.com/file/d/1xgsuvuGcnEYKxuhkFZZeEGLFtjBRdNeZ/view
[JIRA ticket PLACES-211](https://pathcheck.atlassian.net/browse/PLACES-327)
=> [PLACES 327] Filter Data by Record ID

src/ducks/cases/service.js, src/views/Trace/AddNewRecord/index.js
`DELETE /case` to `POST /case/delet￼e`
=> [PLACES-351] Fix new case deletion endpoint

src/components/_shared/RecordsTable/RecordsTablePublishing/Record/index.js, src/components/_shared/RecordsTable/RecordsTableTrace/Record/index.js, src/ducks/points/sagas.js, src/helpers/dateTime.js
Fix in place for reported timestamp formatting issues.
**Publishing**
**Trace**
=> [PLACES 390 & 392] Timestamp formatting

src/components/_shared/RedactorTools/DateSelector/index.js, src/components/_shared/RedactorTools/FilterData/DurationFilter/index.js, src/components/_shared/RedactorTools/FilterData/index.js, src/components/_shared/RedactorTools/index.js, src/components/_shared/SelectedData/SelectedDataContextMenu/index.js, src/components/_shared/SelectedData/index.js, src/ducks/points/actions.js, src/ducks/points/reducer.js, src/ducks/points/selectors.js, src/ducks/points/types.js
Implement Point filters using a selector instead of a stored filteredPoints Array
=> Refactor Filter Logic and implement Duration Filter

src/components/_shared/Map/_helpers.js, src/components/_shared/Map/index.js
Again, more for review than anything else. It does appear to work, though I've not tested extensively.
=> Temporary map/filteredPoints fix

src/components/_shared/RedactorTools/Header/header.module.scss, src/components/_shared/RedactorTools/Header/index.js, src/components/_shared/RedactorTools/index.js, src/ducks/cases/actions.js, src/ducks/cases/reducer.js, src/ducks/cases/sagas.js, src/ducks/cases/selectors.js, src/ducks/cases/types.js
Component breaks publishing view
=> Temporarily drop RecordIds filter

src/components/_shared/Map/index.js, src/components/_shared/PointContextMenu/index.js, src/components/_shared/SelectedData/SelectedDataContextMenu/index.js, src/ducks/cases/sagas.js, src/ducks/points/actions.js, src/ducks/points/reducer.js, src/ducks/points/sagas.js, src/ducks/points/selectors.js, src/ducks/points/types.js, src/helpers/pointsUtils.js
Create a filter to hide case points from the map by adding a `hidden` boolean to points
https://pathcheck.atlassian.net/browse/PLACES-342
=> Unselect Points

src/components/_shared/Map/Marker/Marker.module.scss, src/components/_shared/Map/Marker/index.js
Not sure of the ticket number, but it was something design/product wanted to be implemented on the front-end.
=> Color marker by duration

.eslintrc.json, src/components/PointEditor/index.js, src/components/_global/Navigation/index.js, src/components/_shared/Button/index.js, src/components/_shared/LocationSearch/index.js, src/components/_shared/RecordsTable/RecordsTablePublishing/index.js, src/components/_shared/RecordsTable/RecordsTableTrace/index.js, src/components/_shared/RedactorTools/FilterData/RecordIdsFilter/index.js, src/components/_shared/RedactorTools/Header/index.js, src/components/_shared/SelectedData/SelectedDataContextMenu/index.js, src/components/_shared/SelectedData/index.js, src/views/Authentication/Login/index.js, src/views/Onboarding/HAConfig/DaySlider/index.js, src/views/Onboarding/HAConfig/index.js, src/views/Onboarding/HAConfig/infoInputs.js, src/views/Publish/Actions/LoadActions/index.js, src/views/Publish/Actions/ToolActions/index.js, src/views/Publish/PublishData/index.js, src/views/Settings/index.js, src/views/Trace/Actions/LoadActions/index.js, src/views/Trace/Actions/ToolActions/index.js, src/views/Trace/AddNewRecord/index.js, src/views/Trace/DeletePoints/index.js, src/views/Trace/StageForPublishing/index.js
[QA Spreadsheet](https://docs.google.com/spreadsheets/d/1fMTkcK3MPTv-TljzsKLAHrnmextWODpa2r4ZJxHIReE/edit?usp=sharing)
=> [PLACES-406] Add more IDs for QA team

src/components/_shared/RedactorTools/DateSelector/index.js, src/ducks/points/reducer.js, src/ducks/points/selectors.js, src/helpers/pointsUtils.js
Reset the Date Range and Single Day filter when clearing all point filters
https://pathcheck.atlassian.net/browse/PLACES-442
=> Clear Date Filters on Clear Filters

src/axiosInterceptors.js, src/ducks/auth/actions.js, src/ducks/auth/reducer.js, src/ducks/auth/sagas.js, src/ducks/auth/service.js, src/ducks/auth/types.js
[Ticket](https://pathcheck.atlassian.net/browse/PLACES-462)
=> [PLACES-462] Integrate backend changes in Auth

src/components/_global/Header/header.module.scss, src/components/_global/Navigation/navigation.module.scss, src/components/_global/Notifications/Notification.module.scss, src/components/_global/Notifications/index.js, src/components/_shared/Map/styles.module.scss, src/ducks/auth/sagas.js, src/ducks/points/sagas.js, src/views/Authentication/Login/index.js, src/views/Publish/Publish.module.scss, src/views/Settings/styles.module.scss, src/views/Trace/Tracer.module.scss, src/views/ViewWrapper.module.scss
=> Update notifications styling

src/components/_shared/Map/Marker/Marker.module.scss, src/components/_shared/Map/Marker/index.js, src/components/_shared/PointContextMenu/Body/Body.jsx, src/components/_shared/PointContextMenu/Header/Header.jsx, src/components/_shared/PointContextMenu/LabelAs/LabelAs.jsx, src/components/_shared/PointContextMenu/PointContextMenu.module.scss, src/components/_shared/PointContextMenu/index.js, src/components/_shared/SelectedData/SelectedDataList/SelectedDataItem/SelectedDataItem.jsx, src/helpers/dateTime.js
=> [PLACES 468] Point Contextual Menu updates

src/ducks/cases/sagas.js
- contains fix for [PLACES-478](https://pathcheck.atlassian.net/browse/PLACES-478)
=> dev -> staging

src/components/_shared/Map/DrawEditor/index.js, src/components/_shared/Map/index.js
Current the drawing tools will render for both views, however the publish view is read-only(for now).
=> Only render drawing tools for tracing view

src/components/_shared/RecordsTable/RecordsTablePublishing/Record/index.js, src/components/_shared/RecordsTable/RecordsTablePublishing/Record/record.module.scss, src/components/_shared/RecordsTable/RecordsTablePublishing/index.js
=> Fix records table alignment issues

src/components/_shared/Dialog/Dialog.module.scss, src/components/_shared/RedactorTools/Header/EditRecordModal.js, src/components/_shared/RedactorTools/Header/header.module.scss, src/components/_shared/RedactorTools/Header/index.js
https://pathcheck.atlassian.net/browse/PLACES-474
Before:
After:
I still have to add the checkmark indicator for whether or not the Id is available but that's currently blocked by the backend
=> Edit Record ID Redesign

src/components/_shared/Map/DrawEditor/index.js, src/components/_shared/RecordsTable/RecordsTablePublishing/index.js, src/components/_shared/RecordsTable/RecordsTableTrace/index.js, src/components/_shared/RecordsTable/recordsTable.module.scss, src/components/_shared/RecordsTable/useSortBy.js, src/types/sortBy.js
The user can now sort records by the various dates
**Trace**
**Publish**
[Demo link](https://drive.google.com/file/d/1zxQ6Nckir9lSAteIeTtyDbcvgfMhdTdj/view)
[JIRA ticket](https://pathcheck.atlassian.net/browse/PLACES-479)
=> [PLACES-479] Add sort by date to record tables

src/ducks/cases/sagas.js
I've recent provided a fix for [PLACES-478](https://pathcheck.atlassian.net/browse/PLACES-478), and noticed what appears to be unnecessary code in the GPS data sync. flow.
I don't have much experience with sagas, but I've tested my changes and things function as expected.
=> Remove unnecessary saga

src/components/_shared/ControlledCheckbox/Checkbox.js, src/components/_shared/ControlledCheckbox/styles.module.scss, src/components/_shared/RedactorTools/FilterData/FilterData.module.scss, src/components/_shared/RedactorTools/FilterData/RecordIdsFilter/index.js, src/components/_shared/RedactorTools/FilterData/index.js, src/components/_shared/RedactorTools/index.js, src/components/_shared/SelectedData/SelectedDataList/SelectedDataList.jsx
Enhanced UI + ability to select/unselect all
=> [PLACES-491] Record ID Filter UI

package.json, src/components/_global/Modal/index.js, src/components/_global/Modal/styles.module.scss, src/components/_shared/Loader/index.js, src/components/_shared/PointEditor/PointEditor.module.scss, src/components/_shared/PointEditor/index.js, src/components/_shared/Sidebar/SidebarWrapper/sidebarWrapper.module.scss, src/ducks/cases/sagas.js, src/views/Trace/TraceView.jsx
I've added the [React Transition Group](https://github.com/reactjs/react-transition-group) library to the application - it is the animation library I know best, but if there is a better alternative I am happy to switch before more animations are added to the solution.
**Point Editor**
**Modals**
=> [PLACES-490] UI Animations

src/components/_global/Notifications/Notification.module.scss, src/components/_global/Notifications/index.js
[Demo link](https://drive.google.com/file/d/1Kd-BCmJl1O9lXSnx5Q2xhKHvpLsO1fYL/view)
=> [PLACES-494] Toast animation tweak

src/components/_shared/Map/MapInner.jsx, src/components/_shared/PointContextMenu/Body/Body.jsx, src/components/_shared/PointEditor/index.js, src/components/_shared/SelectedData/SelectedDataList/SelectedDataGroup/SelectedDataGroup.jsx, src/components/_shared/SelectedData/SelectedDataList/SelectedDataItem/_parts/SelectedDataItemInfo.jsx, src/ducks/application/actions.js, src/ducks/application/reducer.js, src/ducks/application/selectors.js, src/ducks/application/types.js, src/ducks/points/actions.js, src/ducks/points/reducer.js, src/ducks/points/sagas.js, src/ducks/points/selectors.js
[Current](https://drive.google.com/file/d/1mbRUyOxglS23qxVtN3XwT4dsO9mUwQob/view)
When dealing with 12000+ points the sidebar will kill/drastically slow the app if the user selects an item in the sidebar.
[Incoming](https://drive.google.com/file/d/1FShN4n-yU8XP2ENVXAf5XyQ5viAukmRf/view)
=> Move activePoint to lighter part of store

tests/docker/testhost/page_objects.py, tests/docker/testhost/ui_test.py, tests/page_objects.py, tests/ui_test.py
Take add data point through publish
=> Ui tests update for UI changes and workflow expansion

src/Router.js, src/components/_global/Modal/ModalSwitch/index.js, src/components/_global/Modal/index.js, src/components/_global/Modal/styles.module.scss, src/components/_shared/Button/index.js, src/components/_shared/Button/styles.module.scss, src/components/_shared/ControlledCheckbox/Checkbox.js, src/components/_shared/Forms/FormWrapper/FormWrapper.jsx, src/components/_shared/Forms/FormWrapper/FormWrapper.module.scss, src/components/_shared/Forms/FormWrapper/index.js, src/components/_shared/PasswordInput/PasswordInput.jsx, src/components/_shared/PasswordInput/PasswordInput.module.scss, src/components/_shared/PasswordInput/index.js, src/components/_shared/PasswordStrengthIndicator/PasswordStrengthIndicator.jsx, src/components/_shared/PasswordStrengthIndicator/PasswordStrengthIndicator.module.scss, src/components/_shared/PasswordStrengthIndicator/_parts/ListItem.jsx, src/components/_shared/PasswordStrengthIndicator/index.js, src/components/_shared/SelectedData/SelectedDataList/SelectedDataItem/_parts/SelectedDataItemActions.jsx, src/ducks/auth/actions.js, src/ducks/auth/sagas.js, src/ducks/auth/service.js, src/ducks/auth/types.js, src/hooks/useValidatePassword.js, src/scss/global.scss, src/views/Authentication/ForgotPassword/ForgotPassword.jsx, src/views/Authentication/ForgotPassword/index.js, src/views/Authentication/Login/index.js, src/views/Authentication/ResetPassword/ResetPassword.jsx, src/views/Authentication/ResetPassword/index.js, src/views/index.js
[Demo link](https://drive.google.com/file/d/14fVXzznfTILpoWqPeZZYNFuenctFTFQu/view)
=> [PLACES-485] Reset Password (UI)

tests/conftest.py, tests/ui_test.py
This PR adds:
- conftest.py file to house pytest fixtures, with the setup fixture moved here
- usage of @pytest.mark.skip to skip tests that are under development
=> using pytest fixtures and marks
